cursor #d4d4d4
cursor_text_color #2a2a2a

foreground #f0f0f0
background #1a1a1a
selection_foreground #2a2a2a
selection_background #b0b0b0
url_color #3FC0C6

color0  #2a2a2a
color8  #4a4a4a

color1  #b0b0b0
color9  #7a7a7a

color2  #b0b0b0
color10 #7a7a7a

color3  #b0b0b0
color11 #7a7a7a

color4  #f0f0f0
color12 #3FC0C6

color5  #b0b0b0
color13 #7a7a7a

color6  #b0b0b0
color14 #167B7E

color7  #d4d4d4
color15 #f0f0f0

background_opacity 0.85
dynamic_background_opacity yes
background_tint 0.0

font_size 12.0
font_family JetBrainsMono Nerd Font
