# Sources section

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybindings.conf

# Exec-once section

exec-once = waybar
exec-once = hyprpaper

input {
    kb_layout = us,ru
    kb_options = grp:win_space_toggle, grp:alt_shift_toggle,
}

general {
    gaps_in = 3
    gaps_out = 3
    border_size = 1
}

decoration {
    rounding = 10
    blur {
      enabled = true
      size = 8
      passes = 3
      new_optimizations = true
      noise = 0.01
      contrast = 1.0
      brightness = 1.0
    }
}
