source = ~/.config/hypr/variables.conf

wallpaper {
    monitor = $mainMonitor
    path = ~/Pictures/wallpapers/
    fit_mode = cover
    timeout = 1800
}

wallpaper {
    monitor = $leftMonitor
    path = ~/Pictures/wallpapers/
    fit_mode = cover
    timeout = 1800
}

splash = false
