# Перемещение между окнами
bind = SUPER, L, movefocus, r
bind = SUPER, H, movefocus, l
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Перемещение окон (перетаскивание в сторону)
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Управление окнами
bind = SUPER, Q, killactive
bind = SUPER, O, togglefloating
bind = SUPER, F, fullscreen, 1 
bind = ALT, Tab, cyclenext


# Ресайз окон
bind = SUPER CTRL, L, resizeactive, 50 0
bind = SUPER CTRL, H, resizeactive, -50 0
bind = SUPER CTRL, K, resizeactive, 0 -50
bind = SUPER CTRL, J, resizeactive, 0 50

# Управление громкостью через функциональные клавиши
#bind = , F11, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
#bind = , F10, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
#bind = , F9, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = SUPER, F12, exec, /home/qu0i/.local/bin/toggle-audio.sh

# Управление воркспейсами
bind = SUPER SHIFT, 1, movecurrentworkspacetomonitor, HDMI-A-1
bind = SUPER SHIFT, 2, movecurrentworkspacetomonitor, DP-1
bind = SUPER SHIFT, TAB, swapactiveworkspaces, HDMI-A-1 DP-1

# Переключение на 1–9 рабочие столы
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, togglespecialworkspace, social
# bind = SUPER, -, togglespecialworkspace, magic

# Переместить окно на рабочий стол
bind = SUPER ALT, 1, movetoworkspace, 1
bind = SUPER ALT, 2, movetoworkspace, 2
bind = SUPER ALT, 3, movetoworkspace, 3
bind = SUPER ALT, 4, movetoworkspace, 4
bind = SUPER ALT, 5, movetoworkspace, 5
bind = SUPER ALT, 6, movetoworkspace, 6
bind = SUPER ALT, 7, movetoworkspace, 7
bind = SUPER ALT, 8, movetoworkspace, 8
bind = SUPER ALT, 9, movetoworkspace, 9
bind = SUPER ALT, 0, movetoworkspace, 0
bind = SUPER ALT, 0, movetoworkspace, special:social
bind = SUPER ALT, -, movetoworkspace, special:magic

# Приложения
bind = SUPER, T, exec, kitty
bind = SUPER, D, exec, wofi --show drun
bind = SUPER, B, exec, firefox
bind = SUPER, W, exec, waterfox
bind = SUPER, INSERT, exec, waybar
bind = SUPER, DELETE, exec, killall waybar
bind = SUPER, N, exec, nemo
bind = SUPER, O, exec, obsidian

# СКРИНЫ
# Папка для скриншотов
exec = mkdir -p ~/Pictures/Screenshots

bind = SUPER, Print, exec, grim -g "$(slurp)" -t png - | tee ~/Pictures/Screenshots/$(date +'%d-%m-%Y_%H-%M').png | wl-copy
bind = SUPER SHIFT, Print, exec, grim -t png - | tee ~/Pictures/Screenshots/$(date +'%d-%m-%Y_%H-%M').png | wl-copy
