source = ~/.config/hypr/variables.conf

monitor = $mainMonitor, $mainMonitorResolution, 0x0, 1
monitor = $leftMonitor, $leftMonitorResolution, -1920x0, 1

workspace = 1, monitor:$mainMonitor, default:true
workspace = 3, monitor:$mainMonitor
workspace = 5, monitor:$mainMonitor

workspace = 2, monitor:$leftMonitor, default:true
workspace = 4, monitor:$leftMonitor
