$mainMod = SUPER

$left = H
$down = J
$up = K
$right = L

$terminal = kitty
$fileManager = nemo
$launcher = wofi --show drun

$mainMonitor = HDMI-A-1
$leftMonitor = DP-1

$mainMonitorResolution = 1920x1080@59.94
$leftMonitorResolution = 1920x1080@60
